# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MTK_CMDQ_MBOX_EXT) += cmdq/
obj-$(CONFIG_MTK_MMINFRA) += mminfra/
obj-$(CONFIG_MTK_BTIF) += btif/
obj-$(CONFIG_MTK_COMBO) += connectivity/
obj-$(CONFIG_MTK_CCCI_MAINLINE) += ccci_util/ ccmni/ eccci/
obj-$(CONFIG_MTK_TINYSYS_SCP_SUPPORT) += scp/
obj-$(CONFIG_MTK_SENSOR_SUPPORT) += sensor/2.0/
