/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2020 MediaTek Inc.
 *
 * Ported from the downstream MediaTek sensor/2.0 stack. The numeric values
 * are part of the SCP sensor-hub ABI: they index the firmware sensor list and
 * the share-memory event records, so they must not be renumbered.
 */

#ifndef _HF_SENSOR_TYPE_H_
#define _HF_SENSOR_TYPE_H_

enum {
	SENSOR_TYPE_INVALID = 0,
	/* follow google default sensor type */
	SENSOR_TYPE_ACCELEROMETER = 1,
	SENSOR_TYPE_MAGNETIC_FIELD,
	SENSOR_TYPE_ORIENTATION,
	SENSOR_TYPE_GYROSCOPE,
	SENSOR_TYPE_LIGHT,
	SENSOR_TYPE_PRESSURE,
	SENSOR_TYPE_TEMPERATURE,
	SENSOR_TYPE_PROXIMITY,
	SENSOR_TYPE_GRAVITY,
	SENSOR_TYPE_LINEAR_ACCELERATION,
	SENSOR_TYPE_ROTATION_VECTOR,
	SENSOR_TYPE_RELATIVE_HUMIDITY,
	SENSOR_TYPE_AMBIENT_TEMPERATURE,
	SENSOR_TYPE_MAGNETIC_FIELD_UNCALIBRATED,
	SENSOR_TYPE_GAME_ROTATION_VECTOR,
	SENSOR_TYPE_GYROSCOPE_UNCALIBRATED,
	SENSOR_TYPE_SIGNIFICANT_MOTION,
	SENSOR_TYPE_STEP_DETECTOR,
	SENSOR_TYPE_STEP_COUNTER,
	SENSOR_TYPE_GEOMAGNETIC_ROTATION_VECTOR,
	SENSOR_TYPE_HEART_RATE,
	SENSOR_TYPE_TILT_DETECTOR,
	SENSOR_TYPE_WAKE_GESTURE,
	SENSOR_TYPE_GLANCE_GESTURE,
	SENSOR_TYPE_PICK_UP_GESTURE,
	SENSOR_TYPE_WRIST_TILT_GESTURE,
	SENSOR_TYPE_DEVICE_ORIENTATION,
	SENSOR_TYPE_POSE_6DOF,
	SENSOR_TYPE_STATIONARY_DETECT,
	SENSOR_TYPE_MOTION_DETECT,
	SENSOR_TYPE_HEART_BEAT,
	SENSOR_TYPE_DYNAMIC_SENSOR_META,
	SENSOR_TYPE_ADDITIONAL_INFO,
	SENSOR_TYPE_LOW_LATENCY_OFFBODY_DETECT,
	SENSOR_TYPE_ACCELEROMETER_UNCALIBRATED,

	/* follow mtk add sensor type */
	SENSOR_TYPE_PEDOMETER = 55,
	SENSOR_TYPE_IN_POCKET,
	SENSOR_TYPE_ACTIVITY,
	SENSOR_TYPE_PDR,
	SENSOR_TYPE_FREEFALL,
	SENSOR_TYPE_FLAT,
	SENSOR_TYPE_FACE_DOWN,
	SENSOR_TYPE_SHAKE,
	SENSOR_TYPE_BRINGTOSEE,
	SENSOR_TYPE_ANSWER_CALL,
	SENSOR_TYPE_GEOFENCE,
	SENSOR_TYPE_FLOOR_COUNTER,
	SENSOR_TYPE_EKG,
	SENSOR_TYPE_PPG1,
	SENSOR_TYPE_PPG2,
	SENSOR_TYPE_RGBW,
	SENSOR_TYPE_GYRO_TEMPERATURE,
	SENSOR_TYPE_SAR,
	SENSOR_TYPE_OIS,
	SENSOR_TYPE_FLICKER,
	SENSOR_TYPE_GYRO_SECONDARY,
	SENSOR_TYPE_PS_FACTORY_STRM,
	SENSOR_TYPE_ALS_FACTORY_STRM,
	SENSOR_TYPE_ELEVATOR_DETECT,
	SENSOR_TYPE_FOD,
	SENSOR_TYPE_AOD,
	SENSOR_TYPE_NONUI,
	SENSOR_TYPE_LUX_B,
	SENSOR_TYPE_FREE_FALL,
	SENSOR_TYPE_LIGHT_SMD,
	SENSOR_TYPE_SAR_ALGO,
	SENSOR_TYPE_SAR_ALGO_1,
	SENSOR_TYPE_SAR_ALGO_2,
	SENSOR_TYPE_DBTAP,
	SENSOR_TYPE_SAR_SECONDARY,
	SENSOR_TYPE_ELLIPTIC_FUSION,
	SENSOR_TYPE_FRONT_CCT,
	SENSOR_TYPE_FRONT_CCT_FACTORY_STRM,
	SENSOR_TYPE_BACK_CCT,
	SENSOR_TYPE_BACK_CCT_FACTORY_STRM,
	SENSOR_TYPE_FLICKER_REAR,
	SENSOR_TYPE_RGBW_REAR,
	SENSOR_TYPE_DUAL_CCT,
	SENSOR_TYPE_TREADMILL,
	SENSOR_TYPE_SMALL_MOVE,
	SENSOR_TYPE_BACK_LUX_STRM,
	SENSOR_TYPE_POCKET,
	SENSOR_TYPE_TRAFFIC_DETECT,
	SENSOR_TYPE_BASEMENT_DETECT,
	SENSOR_TYPE_SCREEN_DOWN,
	SENSOR_TYPE_FLICKER_RAWDATA,
	SENSOR_TYPE_SENSOR_MAX,
};

enum {
	SENSOR_ACCURANCY_UNRELIALE,
	SENSOR_ACCURANCY_LOW,
	SENSOR_ACCURANCY_MEDIUM,
	SENSOR_ACCURANCY_HIGH,
};

/* Event actions carried in the share-memory record "action" field. */
enum {
	DATA_ACTION,
	FLUSH_ACTION,
	BIAS_ACTION,
	CALI_ACTION,
	TEMP_ACTION,
	TEST_ACTION,
	RAW_ACTION,
	MAX_ACTION,
};

/* Sensor descriptor returned by the firmware sensor list. */
struct sensor_info {
	uint8_t sensor_type;
	uint8_t padding[3];
	uint32_t gain;
	char name[16];
	char vendor[16];
} __packed __aligned(4);

#endif
