# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_VIDEO_MEDIATEK_VCP) += mtk-vcp-venc.o
mtk-vcp-venc-y := mtk_vcp_venc.o mtk_vcp_venc_hw.o mtk_vcp_venc_dma.o
obj-$(CONFIG_VIDEO_MEDIATEK_VCP_DEC) += mtk-vcp-vdec.o
mtk-vcp-vdec-y := mtk_vcp_vdec.o mtk_vcp_vdec_hw.o mtk_vcp_vdec_drv.o
